version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: eevariste
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Hello CirlcCi"

workflows:
  my-workflow:
    jobs:
      - hello-job
